# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff22fdae110b5537e8d53a8be38c00e9afc6d12393bbf951545d253df3999b9293263f4c45fa8c78df0c860845639e9724c38a99273a075f522097dc107608af

test:
  secret_key_base: 6c9cca9dc09aeb13d913ef9ce3a84304de81c625c4d476aac54ea845833ddcd1b41b203b55d64624f127d26a83eff8afa266efc43d00aea84a5a4e9974174dde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
